name: my_project_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - beautifulsoup4
  - requests
  - jinja2
  - sqlite
  - scikit-learn
  - spacy
  - pip
  - pip:
    - openai
